name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: ~/.yarn
        key: v1-yarn-deps-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          v1-yarn-deps-

    - name: Install Dependencies
      run: yarn install
    
    ## Test
    - name: Run tests
      run: yarn test:unit

    ## Coverage
    - name: Coverage
      run: yarn test:unit --coverage --coverageReporters=json --collectCoverage=true --coverageDirectory=/coverage

    ## Lint
    - name: Lint JS
      run: yarn lint

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}